name: dartschat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.2
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14
  intl: ^0.19.0
  logger: ^2.0.2
  shared_preferences: ^2.0.15
  rxdart: ^0.27.7
  table_calendar: ^3.0.9
  timezone: ^0.9.0
  flutter_local_notifications: ^17.2.3 # 추가
  http: ^1.2.1  # 최신 버전으로 업데이트

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logo.jpg
    - assets/default_profile.png
    - assets/bulls_fighter.webp
    - assets/dartslive.webp
    - assets/phoenix.webp
    - assets/bronze_1.png
    - assets/bronze_2.png
    - assets/bronze_3.png
    - assets/silver_1.png
    - assets/silver_2.png
    - assets/gold_1.png
    - assets/gold_2.png
    - assets/platinum_1.png
    - assets/platinum_2.png
    - assets/emerald.png
    - assets/diamond.png
    - assets/pro.png
    - lib/l10n/app_en.arb
    - lib/l10n/app_ko.arb
    - lib/l10n/app_ja.arb
    - lib/l10n/app_zh.arb
    - lib/l10n/app_zh_TW.arb
  uses-material-design: true
  generate: true