// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiFC9YNHa0ovynnuzF9K79xgNSuP8BLbE',
    appId: '1:612094009871:web:ba15487f85ddaa88f0797a',
    messagingSenderId: '612094009871',
    projectId: 'dartscircle-ffd63',
    authDomain: 'dartscircle-ffd63.firebaseapp.com',
    storageBucket: 'dartscircle-ffd63.firebasestorage.app',
    measurementId: 'G-HVVF3G4MX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYVJ8RXG4pn3a6m4zRg7mIpJc1VK5hFKo',
    appId: '1:612094009871:android:3b7222293e279c36f0797a',
    messagingSenderId: '612094009871',
    projectId: 'dartscircle-ffd63',
    storageBucket: 'dartscircle-ffd63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlUHsTC5G2DIY1N99JJE6l8-V0HnDvYOs',
    appId: '1:612094009871:ios:3ce989847e031471f0797a',
    messagingSenderId: '612094009871',
    projectId: 'dartscircle-ffd63',
    storageBucket: 'dartscircle-ffd63.firebasestorage.app',
    iosBundleId: 'com.example.dartschat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiFC9YNHa0ovynnuzF9K79xgNSuP8BLbE',
    appId: '1:612094009871:web:e8ef77c67c5b479af0797a',
    messagingSenderId: '612094009871',
    projectId: 'dartscircle-ffd63',
    authDomain: 'dartscircle-ffd63.firebaseapp.com',
    storageBucket: 'dartscircle-ffd63.firebasestorage.app',
    measurementId: 'G-V59Z5BJMF0',
  );
}
